### ISSUE TITLE
Problem with lock 

### ISSUE THREAD

**Issue by gabrielpeixoto** [ben182/laravel-ab#15]
Database: Percona 8.0.15

Exception:
ErrorException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: update `ab_experiments` set `visitors` = `visitors` + 1, `updated_at` = 2019-04-09 15:11:48 where `id` = 1) (View: /var/www/resources/views/user/busca/busca.blade.php)

**Comment by ben182** [comment]
This is probably not a problem with the package. The package will just call the `increment` function of the model and increment an integer. I guess it is a bug with Percona.
