### ISSUE TITLE
not working with Laravel 5.8?

### ISSUE THREAD

**Issue by rickghome** [ben182/laravel-ab#19]
New (empty) laravel project, tried to use your example code, and got error:
```
Call to a member function incrementVisitor() on null
```

**Comment by rickghome** [comment]
ok-- the issue has to do with the config.ab-testing experiments values array. Looks like you have to set that up for this to work, but that's not clear in the docs.

**Comment by ben182** [comment]
Fixed in 1.0.1 by throwing a better exception
