### ISSUE TITLE
Trying to get property 'name' of non-object when crawled

### ISSUE THREAD

**Issue by dmarman** [ben182/laravel-ab#25]
https://github.com/ben182/laravel-ab/blob/059c18500a796ca4093c7507774800d8b0c0f977/src/AbTesting.php#L129

When crawled by Google bot there is no session, so `getExperiment()` won't return an object with a name property. This will break the page and google will see a 500 while normal users have a 200.

Maybe:

```php
public function isExperiment(string $name)
    {
        if ((new CrawlerDetect)->isCrawler()) {
            return false;
        }

        $this->pageView();

        return $this->getExperiment()->name === $name;
    }
```

**Comment by gleman17** [comment]
Ran into the same thing with a dusk test.  There's no session so getExperiment throws an exception.

Quick hack:

return $this->getExperiment()->name??false === $name;

**Comment by gleman17** [comment]
Looks like this repo hasn't seen any activity since Mar 2020, hopefully the author is ok.

I forked it into gleman17/laravel-ab and fixed this bug and will try to catch up with a few others.
